### ISSUE TITLE
Calculate previous measurements again

### ISSUE THREAD

**Issue by thomcz** [thomcz/hrv-band#102]
After updating the app a dialog should popup and inform the user that his measurment will be calculated again, because calculation has been change.

optional: user can disagree?

**Comment by Fenox** [comment]
Vlt. sollten wir die berechneten Werte nicht in der DB speichern, sondern nur die RR-Daten. Stellt man in den Settings irgendetwas um (z.B. Berechnungsmethode oder Abtastrate) müssten jedes mal alle Berechnungen neu durchgerechnet werden.

**Comment by thomcz** [comment]
wie wollen wir das hier jetzt implementieren? Alles in die DB speichern oder immer neu berechnen im hinblick darauf, dass man sich alles mit anderen Methoden nochmal berechnen lassen kann? Wäre für das zweite. Falls es Performanz Probleme gibt, kann man sich ja was überlegen, dass man immer nur 10 lädt und dann weitere 10 (in der Übersicht) usw.

**Comment by thomcz** [comment]
check if your previous measurements are still there if you update
