### ISSUE TITLE
RRInterval mithilfe der Kamera

### ISSUE THREAD

**Issue by thomcz** [thomcz/hrv-band#11]
1. Teste ob man RRInterval aus der Kamera bestimmen kann und wie genau das ist:
   https://github.com/phishman3579/android-heart-rate-monitor
2. In app einbauen

**Comment by Fenox** [comment]
Sollen wir versuchen das in die erste Version zu bringen?
Wenn das wenigstens ein bisschen funktioniert hat gleich einige Leute mehr die die App nutzen könnten.

**Comment by thomcz** [comment]
close, because very inaccurate
