### ISSUE TITLE
Settings: Zeiteinstellung wird nicht direkt übernommen

### ISSUE THREAD

**Issue by Fenox** [thomcz/hrv-band#118]
Wird die dauer der Messung in den Einstellungen übernommen, so wird die Änderung erst nach eiem Neustart übernommen.

**Comment by thomcz** [comment]
bei mir kommt immer eine nachricht, dass die eingabe eine zahl sein muss...

**Comment by Fenox** [comment]
hm das habe ich eigentlich gefixt, kam bei mir auch, kommt aber nicht mehr ich schaue mal, vlt ist es noch nicht commited.

**Comment by Fenox** [comment]
bist du auf dem aktuellen Stand im Master Branch?
dann müsste diese Zeile im Settings Fragment stehen:   
boolean integerParseResult = newRecordLength.matches("[0-9]+");

**Comment by thomcz** [comment]
ok, geht jetzt

**Comment by thomcz** [comment]
wird bei mir immer noch nicht übernommen...muss die app schließen und neu starten

**Comment by Fenox** [comment]
Ich dachte es hätte mal funktioniert?

**Comment by Fenox** [comment]
Hm kannst du einmal probieren die Zeit umzustellen und direkt danach noch einmal auf die Einstellung gehen. Steht dann die neue Zeit da oder wieder die alte?

**Comment by Fenox** [comment]
Bei mir funktioniert es

**Comment by thomcz** [comment]
Steht die neue drin, aber die messung geht noch nach alter zeit

**Comment by Fenox** [comment]
In MeasuringFragment wird die Methode initAnimation() in resetProgress() aufgerufen.
Hier wird die UI reseted. In initAnimation() wird die neue Dauer gesetzt (getDuration()). 
Wird das nicht aufgerufen wenn du zurück zur view kommst? 
Zusätzlich wird initAnimation() noch in onCreateView() aufgerufen. 

Gibt getDuration() den falschen Wert zurück? oder wird es garnicht aufgerufen?

**Comment by thomcz** [comment]
Hab setDuration bevor die messung gestartet wird geschoben. Wenns bei dir immer noch funktioniert kann man den issue schließen

**Comment by Fenox** [comment]
Funktioniert.
