### ISSUE TITLE
SQL Controller Singelton

### ISSUE THREAD

**Issue by thomcz** [thomcz/hrv-band#56]
Change the SQLController into a singelton pattern using enum:
http://stackoverflow.com/questions/26285520/implementing-singleton-with-an-enum-in-java

**Comment by Fenox** [comment]
Zusätzlich zum Singleton möglicherweise die Struktur ändern und die Klassen SQLController und SQLStorageController zusammenführen in eine Klasse, die SQLiteOpenHelper erweitert (Wie [hier](https://guides.codepath.com/android/Local-Databases-with-SQLiteOpenHelper))
