### ISSUE TITLE
First Start Disclaimer

### ISSUE THREAD

**Issue by thomcz** [thomcz/hrv-band#70]
Move Discalimer from first start from MainActivity into SplashActivity.

**Comment by Fenox** [comment]
Hat bei mir nicht so einfach funktionert, es kam eine Fehlermeldung die ich nich wegbekommen habe

**Comment by thomcz** [comment]
Exception? Schreib mal rein hier? Vllt ist's die selbe wie in #7

**Comment by Fenox** [comment]
Ist Derselbe.

**Comment by thomcz** [comment]
close because it won't work
