### ISSUE TITLE
Timeout Ant

### ISSUE THREAD

**Issue by thomcz** [thomcz/hrv-band#78]
If connection to device cannot be established a message should appear after some seconds.

There is already a string, that is used with ms band (error_device_not_connected_help)

**Comment by thomcz** [comment]
if you click in emulator 'connect to msband' a snackbar appears. If you click on 'connect to ant+' nothing happens

**Comment by Fenox** [comment]
Wenn das Band angeschlossen ist?

**Comment by Fenox** [comment]
Problem ist, dass die Snackbar wahrscheinlich irgendwo in dem Background Thread der für das MS Band erstellt wird. Das wollte ich auch mal noch ändern, das alle Geräte-Klassen nur die Listener Benachrichtigen und nicht irgendwelche GUI Sachen machen...

**Comment by Fenox** [comment]
Problem gelöst, auf dem Emulator ist die ANT+ Software nicht installiert. Es wird jetzt die Snackbar wie beim Band angezeigt.
