### ISSUE TITLE
Calculations

### ISSUE THREAD

**Issue by Fenox** [thomcz/hrv-band#85]
Stellt man das Power Spektrum in einem Diagramm dar, sieht es nicht so aus wie es sollte.
Zum Testen habe ich eine HRV Software runtergeladen und die gleichen Daten dort durchlaufen lassen, dabei kamen auch andere Zahlen für die Werte raus, und das Diagramm sah richtig aus.

Die ganze Calculation sollte vlt in ein Eigenes Projekt, sodass man es auch ohne handy und mit einfacherem Datenexport Testen kann.

Ich bekomme vlt. noch eine weitere HRV Software, mit der kann ich das dann auch mal testen.
Es gibt ein ofizielles Datenforamt (IBI) für RR-Intervall Daten.

**Comment by thomcz** [comment]
wir könnten die berechnung als eigenständiges projekt betreiben und in die app als libary einbinden.

**Comment by Fenox** [comment]
Das ist sowie so noch fast alles so wie beim Hackaton (also ziemlich gepfuscht :D )

**Comment by Fenox** [comment]
HRVLib ist in neuem Projekt und wird getestet. Für weitere Fehler mit den Calculations neue Issues öffnen
